IMS/IMS/Models/Equipment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IMS.Models
{
    public class Equipment
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Count { get; set; }
        public DateTime EntryDate { get; set; }

        public static List<Equipment> ListEquipment()
        {
            var list = new List<Equipment>();
            Random random = new Random();

            Equipment equipment;
            for (int i = 0; i < 30; i++)
            {
                equipment = new Equipment();
                equipment.Id=i.ToString();
                equipment.Name = "Item"+i.ToString();
                equipment.Count = random.Next(100).ToString();
                equipment.EntryDate = DateTime.Now;
                list.Add(equipment);
            }
            
            return list;
        }


    }
}

IMS/IMS/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace IMS.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Login()
        {
            ViewBag.msg = "";
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection fm)
        {   
            string username = fm.Get("username");
            string password = fm.Get("password");
            if (username == "admin" && password == "admin")
            {
                Session["username"] = username;
                return RedirectToAction("Index", "DashBoard");
            }
            else
            {
                ViewBag.msg = "Login Failed!!";
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

IMS/IMS/Controllers/DashBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IMS.Controllers
{
    public class DashBoardController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       
    }
}

IMS/IMS/Views/DashBoard/Index.cshtml
@using IMS.Models
@{
    ViewBag.Title = "Dashboard";
}

<script>
    function dialogBox() {
        $("#dialog").dialog();
    }

    // Bind the dialogBox function to the button click event
    $(document).ready(function () {
        $("#openDialog").click(function () {
            dialogBox();
        });
    });
</script>
<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                           
                            Dashboard <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                          
                            Orders
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                          
                            Products
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                          
                            Customers
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                           
                            Reports
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                          
                            Integrations
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main content -->
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

            <!-- Example charts and tables -->
            @{
                List<Equipment> equipment = Equipment.ListEquipment();
            }

            <div class="table-responsive" style="max-width: 45%; max-height: 350px; overflow-y: auto; float: left; border:dotted;padding:5px; border-radius:5px;">
                <strong>Equipment: </strong>
                <button class="btn btn-primary" id="openDialog" style="float:right;">+</button>
                <table class="table table-striped table-sm ">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Count</th>
                            <th>Entry Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Equipment items in equipment)
                        {
                            <tr>
                                <td>@items.Id</td>
                                <td>@items.Name</td>
                                <td>@items.Count</td>
                                <td>@items.EntryDate</td>
                            </tr>

                        }

                        <!-- More rows -->
                    </tbody>
                </table>
            </div>

            <div class="table-responsive" style="max-width: 45%; max-height: 350px; overflow-y: auto; float: right; border:dotted;padding:5px; border-radius:5px; margin:auto;">
                <strong>Equipment: </strong>
                <button class="btn btn-primary" id="openDialog2" style="float:right;">+</button>
                <table class="table table-striped table-sm ">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Count</th>
                            <th>Entry Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Equipment items in equipment)
                        {
                            <tr>
                                <td>@items.Id</td>
                                <td>@items.Name</td>
                                <td>@items.Count</td>
                                <td>@items.EntryDate</td>
                            </tr>

                        }

                        <!-- More rows -->
                    </tbody>
                </table>
            </div>
            @Html.Partial("_PartialView")
        </main>
    </div>
</div>

IMS/IMS/Views/DashBoard/_PartialView.cshtml
<div id="dialog" style="display:none;" title="Dialog Title">
    <p>This is the dialog content.</p>
</div>

IMS/IMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    @*jqury ul link*@

    <script src="~/Scripts/Jqury/jquery-ui.js"></script>
    <link href="~/Scripts/Jqury/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Scripts/Jqury/jquery-ui.theme.min.css" rel="stylesheet" />

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container" style="width:100%">
            @Html.ActionLink("IMS", "Index", "DashBoard", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("DashBoard", "Index", "DashBoard", new { area = "" }, new { @class = "nav-link" })</li>
                    @* <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    @* <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                    <li>@Html.ActionLink("Logout", "Logout", "Auth", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
            <div>
                @{
                    var username = Session["username"];
                    if (username != null)
                    {

                        <span class="navbar-text">Welcome, @username!</span>

                    }
                }
            </div>
        </div>
    </nav>
    <div class="container body-content" style="max-width:100%">


        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*if authentication null then switch to login page*@
    <script>
             (function () {
                 var username = '@Session["username"]';

                 if (!username) {

                     window.location.href = '@Url.Action("Login","Auth")';
                 }

                })();
    </script>
</body>
</html>